config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from rest_framework.authtoken.views import obtain_auth_token

from quzes.frontend import urls as frontend_urls
from quzes.users import urls as users_urls

urlpatterns = [
                  path(settings.ADMIN_URL, admin.site.urls),
                  path('', include(frontend_urls, namespace='frontend')),
                  path('', include(users_urls, namespace='users')),
                  path('accounts/', include('allauth.urls')),
                  # Your stuff: custom urls includes go here
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    # if "debug_toolbar" in settings.INSTALLED_APPS:
    #     import debug_toolbar
    #
    #     urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

quzes/frontend/urls.py
from django.urls import path

from quzes.frontend.views import Home

app_name = 'frontend'
urlpatterns = [
    path('', Home.as_view(), name='home'),
]

quzes/users/urls.py
from django.urls import path

from quzes.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

quzes/answers/models.py
from uuid import uuid4

from django.db import models


class Answers(models.Model):
    uid = models.UUIDField(primary_key=True, editable=False, default=uuid4)
    quiz = models.ForeignKey('quiz.Quiz', on_delete=models.SET_NULL, blank=False, null=True)
    question = models.ForeignKey('questions.Question', on_delete=models.PROTECT, blank=False, null=False)
    interviewee = models.ForeignKey('users.User', on_delete=models.PROTECT, blank=False, null=False)
    value = models.CharField(max_length=100)

    class Meta:
        db_table = 'answers'
        ordering = ['quiz']
        indexes = [
            models.Index(fields=['quiz'], name='quiz_idx'),
            models.Index(fields=['value'], name='value_idx'),
            models.Index(fields=['question'], name='question_idx'),
        ]
        unique_together = [['quiz', 'question']]

quzes/questions/models.py
from uuid import uuid4

from django.db import models


class Question(models.Model):
    uid = models.UUIDField(primary_key=True, editable=False, default=uuid4)
    text = models.TextField()
    name = models.CharField(max_length=100, blank=False, null=True, default=None)
    type = models.CharField(max_length=100)
    required = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)
    exception_date = models.DateField()
    replacement = models.ForeignKey('questions.Question', on_delete=models.SET_NULL, related_name='parent', null=True)
    offer_to_set = models.BooleanField(default=False)

    class Meta:
        db_table = 'questions'

quzes/quiz/models.py
from uuid import uuid4

from django.contrib.postgres.fields import JSONField
from django.db import models

from quzes.questions.models import Question


class Quiz(models.Model):
    uid = models.UUIDField(primary_key=True, editable=False, default=uuid4)
    title = models.CharField(max_length=120)
    pic_title = models.FileField()
    description = models.TextField()
    type = models.CharField(max_length=120)
    creator = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, blank=False)
    questions = models.ManyToManyField(Question)
    rules = JSONField()

    class Meta:
        db_table = 'Quiz'

quzes/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Quzes."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

quzes/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

quzes/answers/views.py
from django.shortcuts import render

# Create your views here.

quzes/frontend/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.views.generic import TemplateView


class Home(TemplateView):
    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, 'pages/home.html', context)

quzes/questions/api/views.py
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.viewsets import GenericViewSet

from .serializers import QuestionsSerializer


class QuestionsViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = QuestionsSerializer
    # queryset = User.objects.all()
    # lookup_field = "username"

    # def get_queryset(self, *args, **kwargs):
    #     return self.queryset.filter(id=self.request.user.id)

    # @action(detail=False, methods=["GET"])
    # def me(self, request):
    #     serializer = UserSerializer(request.user, context={"request": request})
    #     return Response(status=status.HTTP_200_OK, data=serializer.data)

quzes/quiz/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from quzes.quiz.api.serializers import QuizSerializer


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = QuizSerializer
    # queryset = User.objects.all()
    # lookup_field = "username"

    # def get_queryset(self, *args, **kwargs):
    #     return self.queryset.filter(id=self.request.user.id)

    # @action(detail=False, methods=["GET"])
    # def me(self, request):
    #     serializer = UserSerializer(request.user, context={"request": request})
    #     return Response(status=status.HTTP_200_OK, data=serializer.data)

quzes/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

quzes/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

quzes/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Quzes{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Test task for the Facbrick of solutions">
  <meta name="author" content="Alexander Mescheryakov">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
  <![endif]-->

  <link rel="icon" href="{% static 'images/favicons/favicon.png' %}">

  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}
  <!-- Le javascript
  ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
    <!-- Bootstrap JS and its dependencies-->
    {#      <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
    {#      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>#}
    {#      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>#}
    {% include 'includes/css.html' %}
    {% include 'includes/js.html' %}
    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script defer src="{% static 'js/project.js' %}"></script>

  {% endblock javascript %}

</head>

<body>
<div class="mb-3">
  <ul class="nav md-pills nav-justified pills-purple">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'frontend:home' %}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#panel11" role="tab">Active</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#panel12" role="tab">Link 1</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#panel13" role="tab">Link 2</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
         aria-expanded="false"><i class="fas fa-users-cog"></i></a>
      <div class="dropdown-menu dropdown-purple">
        {% if request.user.is_authenticated %}
          <a class="dropdown-item" href="{% url 'users:detail' request.user.username %}"><i class="fas fa-address-card mr-2"></i>Профиль</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt mr-2"></i>Выйти</a>
        {% else %}
          <a id="sign-up-link" class="dropdown-item" href="{% url 'account_signup' %}"><i class="fas fa-sign-out-alt mr-2"></i>Зарегистрироваться</a>
          <a id="log-in-link" class="dropdown-item" href="{% url 'account_login' %}"><i class="fas fa-sign-in-alt mr-2"></i>Войти</a>
        {% endif %}
      </div>
    </li>
  </ul>
</div>


{#    <div class="mb-1">#}
{#      <nav class="navbar navbar-expand-md  navbar-dark bg-dark">#}
{#        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#          <span class="navbar-toggler-icon"></span>#}
{#        </button>#}
{#        <a class="navbar-brand" href="{% url 'frontend:home' %}">Quzes</a>#}
{##}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#          <ul class="navbar-nav mr-auto">#}
{#            <li class="nav-item active">#}
{#              <a class="nav-link" href="{% url 'frontend:home' %}">Home <span class="sr-only">(current)</span></a>#}
{#            </li>#}
{#          </ul>#}
{#        </div>#}
{#      </nav>#}
{##}
{#    </div>#}

<div class="container-fluid">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
          aria-hidden="true">&times;</span></button>
      </div>
    {% endfor %}
  {% endif %}

  {% block content %}
    <!-- Tab panels -->
    <div class="tab-content pt-0">
      <!--Panel 1-->
      <div class="tab-pane fade in show active" id="panel11" role="tabpanel">
        <br>
        panel11
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus
          reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione
          porro voluptate odit minima.</p>

      </div>
      <!--/.Panel 1-->

      <!--Panel 2-->
      <div class="tab-pane fade" id="panel12" role="tabpanel">
        <br>
        panel12
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus
          reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione
          porro voluptate odit minima.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus
          reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione
          porro voluptate odit minima.</p>

      </div>
      <!--/.Panel 2-->

      <!--Panel 3-->
      <div class="tab-pane fade" id="panel13" role="tabpanel">
        <br>
        panel13
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus
          reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione
          porro voluptate odit minima.</p>

      </div>
      <!--/.Panel 3-->
    </div>
  {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

{% block inline_javascript %}
  {# Script tags with only code, no src (defer by default) #}
{% endblock inline_javascript %}
</body>
</html>